DROP SCHEMA IF EXISTS AubergeLegendesBdd;
CREATE SCHEMA AubergeLegendesBdd;
USE AubergeLegendesBdd;

CREATE TABLE Administrateur(
	ID INT NOT NULL AUTO_INCREMENT,
	pseudonyme VARCHAR(240) NOT NULL UNIQUE,
	motDePasse VARCHAR(240) NOT NULL,
	sel VARCHAR(30) NOT NULL,
	CONSTRAINT Utilisateur_PK PRIMARY KEY (ID)
);

CREATE TABLE StatistiquesPrincipales (
	NOM_RACE VARCHAR(240) NOT NULL,
    strenght INT NOT NULL,
    intelligence INT NOT NULL,
    agilite INT NOT NULL,
    constitution INT NOT NULL,
    vigueurMana INT NOT NULL,
    
    CONSTRAINT StatistiquesPrincipales_PK PRIMARY KEY (NOM_RACE)
);

CREATE TABLE StatistiquesSecondaires (
	NOM_CLASSE VARCHAR(240) NOT NULL,
    mele INT NOT NULL,
    projectile INT NOT NULL,
    bouclier INT NOT NULL,
    feu INT NOT NULL,
    glace INT NOT NULL,
    divin INT NOT NULL,
    esquive INT NOT NULL,
    touche INT NOT NULL,
    vitesse INT NOT NULL,
    resistancePhysique INT NOT NULL,
    resistanceElementaire INT NOT NULL,
    resistanceDivine INT NOT NULL,
    
    CONSTRAINT StatistiquesSecondaires_PK PRIMARY KEY (NOM_CLASSE)
);

CREATE TABLE Competence(
	NOM_COMPETENCE VARCHAR(240) NOT NULL,
    estPrincipale boolean NOT NULL,
    cout INT NOT NULL,
    facteurPuissance INT NOT NULL,
    degats INT NOT NULL,
    typeDeDegats VARCHAR(240) NOT NULL,
    
    CONSTRAINT Competence_PK PRIMARY KEY (NOM_COMPETENCE)    
);

CREATE TABLE Personnage (
	ID_PERSONNAGE INT NOT NULL AUTO_INCREMENT, 
    nom VARCHAR(240),
	pv INT NOT NULL DEFAULT 0,
    mana INT NOT NULL DEFAULT 0,
    nombreDeSelection INT DEFAULT 0,
    nombreDeMatchGagne INT DEFAULT 0,
    nombreDeMatchPerdu INT DEFAULT 0,
    NOM_RACE VARCHAR(240) NOT NULL,
    NOM_CLASSE VARCHAR(240) NOT NULL,
    NOM_COMPETENCE1 VARCHAR(240) NOT NULL,
    NOM_COMPETENCE2 VARCHAR(240) NOT NULL,
    NOM_COMPETENCE3 VARCHAR(240) NOT NULL,
    NOM_COMPETENCE4 VARCHAR(240) NOT NULL,
    CONSTRAINT Personnage_PK PRIMARY KEY (ID_PERSONNAGE),
    CONSTRAINT Personnage_StatistiquesPrincipales_FK FOREIGN KEY (NOM_RACE) REFERENCES StatistiquesPrincipales(NOM_RACE),
    CONSTRAINT Personnage_StatistiquesSecondaires_FK FOREIGN KEY (NOM_CLASSE) REFERENCES StatistiquesSecondaires(NOM_CLASSE),
    CONSTRAINT Personnage_Competence_FK1 FOREIGN KEY (NOM_COMPETENCE1) REFERENCES Competence(NOM_COMPETENCE),
    CONSTRAINT Personnage_Competence_FK2 FOREIGN KEY (NOM_COMPETENCE2) REFERENCES Competence(NOM_COMPETENCE),
    CONSTRAINT Personnage_Competence_FK3 FOREIGN KEY (NOM_COMPETENCE3) REFERENCES Competence(NOM_COMPETENCE),
    CONSTRAINT Personnage_Competence_FK4 FOREIGN KEY (NOM_COMPETENCE4) REFERENCES Competence(NOM_COMPETENCE)
);

CREATE TABLE Utilisateur (
	ID_UTILISATEUR INT NOT NULL AUTO_INCREMENT,
    ID_PERSONNAGE INT,
	pseudonyme VARCHAR(240) NOT NULL UNIQUE,
	motDePasse VARCHAR(240) NOT NULL,
    adresseIP VARCHAR(240) NOT NULL,
    banni CHAR(1),
	CONSTRAINT Utilisateur_PK PRIMARY KEY (ID_UTILISATEUR),
    CONSTRAINT Utilisateur_Personnage_FK4 FOREIGN KEY (ID_PERSONNAGE) REFERENCES Personnage(ID_PERSONNAGE)
);

CREATE TABLE Combat (
	ID_COMBAT INT NOT NULL AUTO_INCREMENT,
	nombreDeTour INT NOT NULL,
	ID_GAGNANT INT,
    ID_PERDANT INT,
	CONSTRAINT Combat_PK PRIMARY KEY (ID_COMBAT),
	CONSTRAINT Combat_Utilisateur_FK FOREIGN KEY (ID_GAGNANT) REFERENCES Personnage(ID_PERSONNAGE),
    CONSTRAINT Combat_UtilisateurL_FK FOREIGN KEY (ID_PERDANT) REFERENCES Personnage(ID_PERSONNAGE)
);

CREATE TABLE TourDeCombat (
	ID_TOUR_COMBAT INT NOT NULL AUTO_INCREMENT,
    ID_UTILISATEUR_ATTAQUANT INT NOT NULL,
    ID_UTILISATEUR_DEFENSEUR INT NOT NULL,
    esquive CHAR(1) NOT NULL,
    NOM_COMPETENCE VARCHAR(240) NOT NULL,
    degats INT,
    CONSTRAINT TourDeCombat_PK PRIMARY KEY (ID_TOUR_COMBAT),
    CONSTRAINT TourDeCombat_UtilisateurAtt_FK FOREIGN KEY (ID_UTILISATEUR_ATTAQUANT) REFERENCES Utilisateur(ID_UTILISATEUR),
    CONSTRAINT TourDeCombat_UtilisateurDef_FK FOREIGN KEY (ID_UTILISATEUR_DEFENSEUR) REFERENCES Utilisateur(ID_UTILISATEUR),
    CONSTRAINT TourDeCombat_Competence_FK FOREIGN KEY (NOM_COMPETENCE) REFERENCES Competence(NOM_COMPETENCE)
);

CREATE TABLE hommePoireauTue(
	ID INT NOT NULL AUTO_INCREMENT,
    nbVictimes INT,
    CONSTRAINT hommePoireauTue_PK PRIMARY KEY (ID)
);